# Generated by Django 3.2.6 on 2021-08-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectAnswer',
            new_name='ElegirRespuesta',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Pregunta',
        ),
    ]
