# Generated by Django 3.2.6 on 2021-08-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20210822_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?')),
                ('text', models.TextField(verbose_name='Contenido de la respuesta')),
            ],
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='text',
            field=models.TextField(verbose_name='Contenido de la pregunta'),
        ),
        migrations.DeleteModel(
            name='ElegirRespuesta',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Quiz.pregunta'),
        ),
    ]
