# Generated by Django 3.2.6 on 2021-08-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20210822_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='text',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='correct',
            new_name='correcta',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='question',
            new_name='pregunta',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='text',
            new_name='texto',
        ),
    ]
