# Generated by Django 3.2.6 on 2021-08-22 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0004_auto_20210822_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.IntegerField(default=0, verbose_name='Puntaje Total')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasRespondidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?')),
                ('puntaje', models.IntegerField(default=0, verbose_name='Puntaje obtenido')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.usuario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Quiz.respuesta')),
            ],
        ),
    ]
