# Generated by Django 3.2.6 on 2021-08-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_alter_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizusuario',
            name='puntaje_total',
            field=models.IntegerField(default=0, null=True, verbose_name='Puntaje Total'),
        ),
    ]
