# Generated by Django 3.2.6 on 2021-08-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_quizusuario_puntaje_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='respuesta',
        ),
    ]
