# Generated by Django 3.2.6 on 2021-08-29 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_remove_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.respuesta'),
        ),
    ]
