# Generated by Django 3.2.6 on 2021-08-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='respuesta',
        ),
    ]
