# Generated by Django 3.2.6 on 2021-08-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestasList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.respuestaslist'),
        ),
    ]
