# Generated by Django 3.2.6 on 2021-08-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_auto_20210829_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_intento', to='Quiz.pregunta'),
        ),
    ]
