# Generated by Django 3.2.6 on 2021-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_alter_preguntasrespondidas_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Puntaje máximo'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje Obtenido'),
        ),
        migrations.AlterField(
            model_name='quizusuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje Total'),
        ),
    ]
