# Generated by Django 3.2.6 on 2021-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_auto_20210829_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizusuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Puntaje Total'),
        ),
    ]
