# Generated by Django 3.2.6 on 2021-08-29 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0016_alter_quizusuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizusuario',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ManyToManyField(to='Quiz.Respuesta'),
        ),
    ]
