# Generated by Django 3.2.6 on 2021-08-29 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0017_auto_20210829_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizusuario',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
