# Generated by Django 3.2.6 on 2021-08-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0018_rename_created_at_quizusuario_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizusuario',
            old_name='created_at',
            new_name='fecha_de_creacion',
        ),
    ]
